# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e680c9e35576664784036ba401f2a23fb81424e2de4e95c3c3b9886cccb289df67d41ed6e7daec91ea714820b7f450dc5178fe9ac494d86b49582dbd4eed5661

test:
  secret_key_base: a5d97c936945ace8e6f14f8dbc94d2964a840bb1e913d9ac24e7bc14f79d86b181ef5710df710185ef15eacd2f5aa0a20e98ab55c13d93b5fabf3a83981667e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
